### ISSUE TITLE
Weird escaping of asterisk in Markdown

### ISSUE THREAD

**Issue by ledsoft** [lukaskabc/spring-boot-configuration-docgen#1]
The Markdown output marks required configuration properties with `**\***` which then renders as `*****`. This does not seem to be correct, simple `\*` can be used to escape the asterisk character. Or perhaps I misunderstood the behavior?

**Comment by lukaskabc** [comment]
The intention was a bold asterisk **\***, which was rendered correctly according to my [tests](https://github.com/lukaskabc/spring-boot-configuration-docgen/blob/main/processor-tests/src/test/resources/configuration_tests_expected_outputs/md/JSR303AllConstraintsConfiguration.md).

This can be customized with a custom template.
Default asterisk directive: [link](https://github.com/lukaskabc/spring-boot-configuration-docgen/blob/main/processor/src/main/resources/templates/directives.txt)
Default MD template: [link](https://github.com/lukaskabc/spring-boot-configuration-docgen/blob/main/processor/src/main/resources/templates/table.md?plain=1)

Overriding the asterisk macro should be possible like this (removed the bold format)
```
[#macro asterisk option][#compress]
[#-- check if the option is required --]

    [#if option.required]
        [#assign areThereRequired = true]

[#-- adjust the output format and use #t to strip new lines and spaces --]

        [#if format == "MD"]
            \*
        [#else]
            &#42;
        [/#if]

    [/#if]
[/#compress][/#macro]
```
I am unsure about interaction with the variable and printing the legend at the end of the template.
[This](https://freemarker-user.narkive.com/cicP63GS/possible-to-override-import-macro-in-namespace) might be related in that case.

**Comment by ledsoft** [comment]
Ok, I see. So the problem was just the IntelliJ markdown preview renderer. Closing the issue, thanks for the explanation.
