### ISSUE TITLE
Add support to create output directories when they do not exists

### ISSUE THREAD

**Issue by blcham** [lukaskabc/spring-boot-configuration-docgen#2]
if `configurationdoc.output_file` points to a directory that does not exist, it fails. It would be nice to have configuration parameter such as: 
`configurationdoc.create_output_directory_if_notexists=true`

This would create the directory even if it does not exist.

My motivation was to remove the following line:
https://github.com/kbss-cvut/record-manager/blob/23545a65c6069e3fe1f79f101036e2ec6c4594b9/Dockerfile#L11C6-L11C30

**Comment by lukaskabc** [comment]
Thank you for the report.
A new version [`1.1`](https://central.sonatype.com/artifact/cz.lukaskabc.cvut.processor/spring-boot-configuration-docgen-processor/1.1) should be available.

I have not added the configuration option. 
A directory will always be created if it doesn't exist.

**Comment by blcham** [comment]
thank you!
